### ISSUE TITLE
papers: add citesummary for papers

### ISSUE THREAD

**Issue by eamonnmag** [inspirehep/inspire-citesummary-js#1]
This will only show the citations, not paper information, since there is only one.

**Comment by jacquerie** [comment]
Sorry, I don't understand: is this issue about writing the backend for `literature`, or is it about something missing in the library?

**Comment by eamonnmag** [comment]
This is all about what I'm doing. Nothing for the back end will be referenced here. That's required of course, but not in this repo.

**Comment by jacquerie** [comment]
Ok. I was asking because I couldn't find anything missing from here : )

**Comment by jacquerie** [comment]
> BTW, in ~30 minutes I can show you a prototype of this guy's backend.

https://github.com/jacquerie/inspire-next/commit/d02bb5016c6b62f1e733bb9e3b797f84c35b369c
